### PR TITLE
update drop down menus

### PR DESCRIPTION
**Pull request by radhikajain**
update drop down menus

### CODE REVIEW

**Comment by justinrporter** [comment]
You've actually cloned our repo on your own account, here @radhikajain , which I think didn't mean to do. That's probably partly my fault, since I may have not granted you push access to this repo. It's fine (I'm dealing with it now), but for next time you'll know!

**Comment by radhikajain** [comment]
I don’t think I’ll know for next time, because I have no idea how I did that… Very likely it will happen again. 


Gosh and I was so proud of myself for all the work I did too…

**Comment by justinrporter** [comment]
Don't worry! You did a great job! We'll chat about later. Easy mistake to make, and an easy mistake to fix!

**Comment by radhikajain** [comment]
I have a few more changes to make tonight, should I wait until you show me how to not clone the repository, or just keep adding them to the same branch?

**Comment by Talophex** [comment]
I think you're fine continuing the same branch, it's very easy to merge things in!

**Comment by justinrporter** [comment]
yeah it's just kind of annoying because it's much more work to check out her repo and test stuff than it would be to check out a branch in our repo...

**Pull request merged**
